### ISSUE TITLE
@bookable.schedule method missing

### ISSUE THREAD

**Issue by iliaboti** [tandusrl/acts_as_bookable#18]
Hi,

I am trying to use acts_as_bookable with Rails5 and I see that @bookable.schedule gives me NoMethodError: undefined method `schedule' for ...

FYI..
@bookable.booking_opts
 => {:time_type=>:fixed, :capacity_type=>:none, :bookable_across_occurrences=>false}

Also note that I am using the influitive/apartment gem -> https://github.com/influitive/apartment

Thanks for your help,
Ioannis

**Comment by Chosko** [comment]
Hi,

to use the  :time_type option your bookable class must have a "schedule"
field.
You should generate (and run) a migration to add that "schedule" column of
type "text" to your bookable table. It's all explained in the readme.
Tell me if that helps, or if you need additional assistance.

Il 18 dic 2016 9:43 PM, "iliaboti" <notifications@github.com> ha scritto:

**Comment by iliaboti** [comment]
Thanks! You are absolutely right. The documentation mentions this requirement for creating  the relevant column. Apologies for not seeing it. 
I am now a step further and trying to use the gem.
Thanks a lot for your work and your answer.
